# Generated by Django 4.2.13 on 2024-08-17 18:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0003_gallery_title_alter_gallery_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gallery',
            name='title',
        ),
    ]
