# Generated by Django 4.2.13 on 2024-08-13 17:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0002_remove_teacher_specialization'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacher',
            name='birth_date',
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='experience',
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='faculty',
        ),
    ]
