# Generated by Django 4.2.13 on 2024-08-19 07:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0005_alter_teacher_phone_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacher',
            name='phone_number',
        ),
    ]
