# Generated by Django 4.2.13 on 2024-08-19 07:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('personal', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='personal',
            name='phone_number',
        ),
    ]
