# Generated by Django 4.2.13 on 2024-08-14 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Link',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link_tiktok', models.CharField(max_length=250)),
                ('link_instagram', models.CharField(max_length=250)),
                ('link_facebook', models.CharField(max_length=250)),
                ('link_twitter', models.CharField(max_length=250)),
            ],
        ),
    ]
