# Generated by Django 4.2.13 on 2024-08-19 11:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('link', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='link',
            old_name='link_tiktok',
            new_name='link_youtube',
        ),
    ]
